import { env } from 'cloudflare:workers';
import { defaults, fields, renderPortfolio, validateData, type DocumentData } from './content';
const bindings=()=>env as unknown as {DB:D1Database;BUCKET:R2Bucket;EDITOR_PASSWORD_HASH?:string};
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
const now=()=>Math.floor(Date.now()/1000);
const hex=(bytes:ArrayBuffer)=>Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');
const fromHex=(value:string)=>Uint8Array.from(value.match(/../g)||[],b=>parseInt(b,16));
export async function digest(value:string){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))}
function same(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
export function json(value:unknown,status=200,headers:Record<string,string>={}){return Response.json(value,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}})}
export function requireOrigin(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin||req.headers.get('sec-fetch-site')==='cross-site')throw new HttpError(403,'This request must come from your website.');}
export async function bounded(req:Request,max:number){if(Number(req.headers.get('content-length')||0)>max)throw new HttpError(413,'This file or request is too large.');const reader=req.body?.getReader();if(!reader)return new Uint8Array();const chunks:Uint8Array[]=[];let size=0;while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>max){await reader.cancel();throw new HttpError(413,'This file or request is too large.')}chunks.push(r.value)}const data=new Uint8Array(size);let offset=0;for(const chunk of chunks){data.set(chunk,offset);offset+=chunk.length}return data;}
async function bodyJSON(req:Request,max=1000000){if(!req.headers.get('content-type')?.startsWith('application/json'))throw new HttpError(415,'Use a JSON request.');try{return JSON.parse(new TextDecoder().decode(await bounded(req,max)))}catch(e){if(e instanceof HttpError)throw e;throw new HttpError(400,'Invalid request.')}}
function sessionCookie(req:Request){const u=new URL(req.url);const local=u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname);return {name:local?'portfolio_editor_local':'__Host-portfolio_editor',secure:local?'':' Secure;'};}
export async function requireSession(req:Request){const name=sessionCookie(req).name;const token=req.headers.get('cookie')?.match(new RegExp('(?:^|;\\s*)'+name+'=([a-f0-9]{64})(?:;|$)'))?.[1];if(!token)throw new HttpError(401,'Please unlock the editor.');const row=await bindings().DB.prepare('SELECT token_hash FROM editor_sessions WHERE token_hash = ? AND expires > ?').bind(await digest(token),now()).first();if(!row)throw new HttpError(401,'Your session expired. Please unlock the editor again.');return token;}
async function rateLimit(req:Request){const ip=req.headers.get('cf-connecting-ip')||'unknown';const window=Math.floor(now()/900);const key=await digest(ip)+':'+window;const db=bindings().DB;const rows=await db.batch<{count:number}>([db.prepare('INSERT INTO login_attempts (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,now()+900),db.prepare('INSERT INTO login_attempts (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind('global:'+window,now()+900),db.prepare('DELETE FROM login_attempts WHERE expires < ?').bind(now()-900),db.prepare('DELETE FROM editor_sessions WHERE expires < ?').bind(now())]);if(Number(rows[0].results[0]?.count)>10||Number(rows[1].results[0]?.count)>300)throw new HttpError(429,'Too many attempts. Please try again in 15 minutes.');}
export async function login(req:Request){requireOrigin(req);await rateLimit(req);const input=await bodyJSON(req,4096);const stored=bindings().EDITOR_PASSWORD_HASH;if(!stored)throw new HttpError(503,'Private access is not configured.');const [salt,expected]=stored.split(':');if(!/^[a-f0-9]{32}$/.test(salt)||!/^[a-f0-9]{64}$/.test(expected))throw new HttpError(503,'Private access is not configured.');if(typeof input.password!=='string'||input.password.length>200)throw new HttpError(401,'Incorrect password.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(input.password),'PBKDF2',false,['deriveBits']);const actual=hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:fromHex(salt),iterations:100000,hash:'SHA-256'},key,256));if(!same(actual,expected))throw new HttpError(401,'Incorrect password.');const token=hex(crypto.getRandomValues(new Uint8Array(32)).buffer);await bindings().DB.prepare('INSERT INTO editor_sessions (token_hash,expires) VALUES (?,?)').bind(await digest(token),now()+43200).run();return json({ok:true},200,{'Set-Cookie':`${sessionCookie(req).name}=${token}; Path=/;${sessionCookie(req).secure} HttpOnly; SameSite=Strict; Max-Age=43200`});}
export async function logout(req:Request){requireOrigin(req);const token=await requireSession(req);await bindings().DB.prepare('DELETE FROM editor_sessions WHERE token_hash=?').bind(await digest(token)).run();return json({ok:true},200,{'Set-Cookie':`${sessionCookie(req).name}=; Path=/;${sessionCookie(req).secure} HttpOnly; SameSite=Strict; Max-Age=0`});}
export async function readContent(){const row=await bindings().DB.prepare('SELECT version,data,updated_at FROM portfolio_content WHERE id=1').first<{version:number;data:string;updated_at:number}>();if(!row)return {version:0,data:defaults(),updatedAt:null};return {version:row.version,data:JSON.parse(row.data) as DocumentData,updatedAt:row.updated_at};}
export async function editorData(req:Request){await requireSession(req);return json({...await readContent(),fields});}
export async function publish(req:Request){requireOrigin(req);await requireSession(req);const input=await bodyJSON(req);if(!Number.isSafeInteger(input.version)||input.version<0)throw new HttpError(400,'Invalid version.');let data;try{data=validateData(input.data)}catch(e){throw new HttpError(400,(e as Error).message)}const db=bindings().DB;await db.prepare('INSERT OR IGNORE INTO portfolio_content (id,version,data,updated_at) VALUES (1,0,?,?)').bind(JSON.stringify(defaults()),now()).run();const result=await db.prepare('UPDATE portfolio_content SET version=version+1,data=?,updated_at=? WHERE id=1 AND version=? RETURNING version,updated_at').bind(JSON.stringify(data),now(),input.version).first<{version:number;updated_at:number}>();if(!result)throw new HttpError(409,'This website was updated in another session. Copy your unsaved changes, then reload the editor.');return json({version:result.version,updatedAt:result.updated_at});}
export async function upload(req:Request){requireOrigin(req);await requireSession(req);const bytes=await bounded(req,11*1024*1024);let form:FormData;try{form=await new Request(req.url,{method:'POST',headers:{'content-type':req.headers.get('content-type')||''},body:bytes}).formData()}catch{throw new HttpError(400,'Choose a supported image.')}const file=form.get('image');if(!(file instanceof File)||file.size>10*1024*1024||file.size<12)throw new HttpError(400,'Choose an image smaller than 10 MB.');const body=await file.arrayBuffer();const b=new Uint8Array(body);const sig=(s:string,offset=0)=>[...s].every((c,i)=>b[offset+i]===c.charCodeAt(0));let type='';if(b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)type='image/jpeg';else if(b[0]===137&&sig('PNG\r\n\x1a\n',1))type='image/png';else if(sig('RIFF')&&sig('WEBP',8))type='image/webp';else if(sig('GIF87a')||sig('GIF89a'))type='image/gif';if(!type)throw new HttpError(415,'Use a JPG, PNG, WebP or GIF image.');const key=crypto.randomUUID();await bindings().BUCKET.put(key,body,{httpMetadata:{contentType:type},customMetadata:{uploadedAt:String(now())}});return json({src:'/media/'+key});}
export async function media(key:string){if(!/^[a-f0-9-]{36}$/.test(key))return new Response('Not found',{status:404});const file=await bindings().BUCKET.get(key);if(!file)return new Response('Not found',{status:404});return new Response(file.body,{headers:{'Content-Type':file.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'"}});}
export async function publicPage(){const {data}=await readContent();return new Response(renderPortfolio(data),{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'self'; form-action 'self'"}});}
export async function handled(fn:()=>Promise<Response>){try{return await fn()}catch(e){return json({error:e instanceof HttpError?e.message:'Something went wrong. Please try again.'},e instanceof HttpError?e.status:500)}}
