'use client';
import { useEffect, useMemo, useState } from 'react';
import { LockKeyhole, ArrowLeft, ExternalLink, Upload, LogOut, Check, ArrowUp, ArrowDown, X, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import type { DocumentData, Field, GalleryImage } from '@/lib/content';
type State={version:number;data:DocumentData;fields:Field[];updatedAt:number|null};
async function request(path:string,options:RequestInit={}){const r=await fetch(path,{credentials:'same-origin',...options});const body:any=await r.json();if(!r.ok)throw Object.assign(new Error(body.error||'Please try again.'),{status:r.status});return body;}
export default function Editor(){
 const [state,setState]=useState<State|null>(null),[loading,setLoading]=useState(true),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false),[group,setGroup]=useState('All sections'),[query,setQuery]=useState(''),[uploading,setUploading]=useState('');
 useEffect(()=>{request('/api/editor').then(setState).catch(e=>{if(e.status!==401)setError(e.message)}).finally(()=>setLoading(false))},[]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',guard);return()=>removeEventListener('beforeunload',guard)},[dirty]);
 const groups=useMemo(()=>['All sections',...new Set(state?.fields.map(f=>f.group)||[])],[state?.fields]);
 const filtered=useMemo(()=>state?.fields.filter(f=>(group==='All sections'||f.group===group)&&(!query||(f.label+' '+f.group+' '+(f.type==='image'?'':state.data.values[f.id])).toLowerCase().includes(query.toLowerCase())))||[],[state,group,query]);
 function update(id:string,value:string){setState(s=>s&&({...s,data:{...s.data,values:{...s.data.values,[id]:value}}}));setDirty(true);setNotice('')}
 function contact(key:keyof DocumentData['contact'],value:string){setState(s=>s&&({...s,data:{...s.data,contact:{...s.data.contact,[key]:value}}}));setDirty(true);setNotice('')}
 function gallery(key:string,list:GalleryImage[]){setState(s=>s&&({...s,data:{...s.data,galleries:{...s.data.galleries,[key]:list}}}));setDirty(true);setNotice('')}
 async function unlock(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{await request('/api/editor/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});setPassword('');setState(await request('/api/editor'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function publish(){if(!state)return;setBusy(true);setError('');setNotice('');try{const result=await request('/api/editor',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:state.version,data:state.data})});setState(s=>s&&({...s,...result}));setDirty(false);setNotice('Your changes are live. Visitors will see them when they open or refresh the website.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function logout(){if(dirty&&!confirm('Discard your unpublished changes and sign out?'))return;try{await request('/api/editor/logout',{method:'POST'});setState(null);setDirty(false);setNotice('')}catch(e){setError((e as Error).message)}}
 async function upload(file:File|undefined,key:string,done:(src:string)=>void){if(!file)return;if(file.size>10*1024*1024){setError('Choose an image smaller than 10 MB.');return}if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){setError('Use a JPG, PNG, WebP or GIF image.');return}setUploading(key);setError('');try{const form=new FormData();form.set('image',file);const result=await request('/api/editor/upload',{method:'POST',body:form});done(result.src);setNotice('Image uploaded. Publish changes when you are ready.')}catch(e){setError((e as Error).message)}finally{setUploading('')}}
 if(loading)return <main className="access-screen"><p role="status">Opening private access…</p></main>;
 if(!state)return <main className="access-screen"><form className="access-card" onSubmit={unlock}><a className="quiet-link" href="/"><ArrowLeft size={16}/> Back to website</a><div className="lock-mark"><LockKeyhole size={25}/></div><h1>Private access</h1><p>Enter your password to continue.</p><label htmlFor="password">Password</label><Input id="password" type="password" autoComplete="current-password" required maxLength={200} value={password} onChange={e=>setPassword(e.target.value)} autoFocus/><Button type="submit" disabled={busy}>{busy?'Unlocking…':'Unlock'}</Button>{error&&<p className="error" role="alert">{error}</p>}</form></main>;
 return <div className="editor-shell"><header className="editor-header"><div><p className="kicker">MUHAMMAD TAHA</p><h1>Website editor</h1></div><div className="editor-actions"><a href="/" target="_blank" rel="noopener noreferrer" className="quiet-link">View website <ExternalLink size={16}/></a><Button variant="outline" onClick={logout} disabled={busy||!!uploading}><LogOut size={16}/><span>Sign out</span></Button><Button onClick={publish} disabled={!dirty||busy||!!uploading}>{busy?'Publishing…':dirty?'Publish changes':'Up to date'}{!dirty&&<Check size={16}/>}</Button></div></header>
 <div className="save-status"><span>{dirty?'Unpublished changes':state.updatedAt?'Last published '+new Date(state.updatedAt*1000).toLocaleString():'Your current portfolio is ready to edit.'}</span>{notice&&<p role="status">{notice}</p>}{error&&<p className="error" role="alert">{error}</p>}</div>
 <div className="editor-body"><aside className="editor-sidebar"><label className="search-label" htmlFor="search"><Search size={16}/> Find content</label><Input id="search" placeholder="Search text or project…" value={query} onChange={e=>setQuery(e.target.value)}/><nav aria-label="Content sections">{groups.map(name=><Button key={name} variant={group===name?'secondary':'ghost'} aria-pressed={group===name} onClick={()=>setGroup(name)}>{name}</Button>)}</nav></aside>
 <main className="editor-main"><Tabs defaultValue="text"><TabsList className="editor-tabs" aria-label="Content type"><TabsTrigger value="text">Text</TabsTrigger><TabsTrigger value="images">Images</TabsTrigger><TabsTrigger value="links">Links</TabsTrigger><TabsTrigger value="contact">Contact</TabsTrigger><TabsTrigger value="galleries">Case studies</TabsTrigger></TabsList>
 <TabsContent value="text"><div className="tab-intro"><h2>Words & information</h2><p>Edit headings, descriptions, services, experience, labels, and search information.</p></div><div className="field-list">{filtered.filter(f=>['text','attribute'].includes(f.type)).map(f=><div className="field-card" key={f.id}><span className="field-group">{f.group}</span><label htmlFor={f.id}>{f.label}</label><Textarea id={f.id} rows={state.data.values[f.id].length>220?5:2} maxLength={f.type==='text'?20000:3000} value={state.data.values[f.id]} disabled={busy} onChange={e=>update(f.id,e.target.value)}/></div>)}{!filtered.some(f=>['text','attribute'].includes(f.type))&&<p className="empty">No matching text in this section.</p>}</div></TabsContent>
 <TabsContent value="images"><div className="tab-intro"><h2>Images & descriptions</h2><p>Each card is one image placement. Replace its artwork and describe it for accessibility. Update illustrative-preview notes in the Text tab when adding original work.</p></div><div className="image-grid">{filtered.filter(f=>f.type==='image').map(f=><article className="image-card" key={f.id}><div className="image-preview"><img src={state.data.values[f.id]} alt={f.altId?state.data.values[f.altId]:f.label}/></div><div className="image-controls"><span className="field-group">{f.group}</span><h3>{f.label}</h3><label htmlFor={'upload-'+f.id}><Upload size={16}/> {uploading===f.id?'Uploading…':'Replace image'}</label><Input id={'upload-'+f.id} type="file" accept="image/png,image/jpeg,image/webp,image/gif" disabled={!!uploading||busy} onChange={e=>{upload(e.target.files?.[0],f.id,src=>update(f.id,src));e.target.value=''}}/>{f.altId&&<><label htmlFor={f.altId}>Image description</label><Textarea id={f.altId} value={state.data.values[f.altId]} disabled={busy} onChange={e=>update(f.altId!,e.target.value)}/></>}</div></article>)}</div>{!filtered.some(f=>f.type==='image')&&<p className="empty">No images in this section. Choose another section.</p>}</TabsContent>
 <TabsContent value="links"><div className="tab-intro"><h2>Links</h2><p>Change external link destinations here. Email, phone, WhatsApp, Instagram, and LinkedIn are together in Contact.</p></div>{filtered.filter(f=>f.type==='link').map(f=><div className="field-card" key={f.id}><span className="field-group">{f.group}</span><label htmlFor={f.id}>{f.label}</label><Input id={f.id} value={state.data.values[f.id]} disabled={busy} onChange={e=>update(f.id,e.target.value)}/></div>)}{!filtered.some(f=>f.type==='link')&&<p className="empty">No other external links in this section.</p>}</TabsContent>
 <TabsContent value="contact"><div className="tab-intro"><h2>Contact details</h2><p>These settings update your visible contact information and the WhatsApp project form together.</p></div>{([['email','Email address'],['whatsapp','WhatsApp number — country code and digits only'],['displayNumber','Phone number as shown on the website'],['instagram','Instagram profile URL'],['linkedin','LinkedIn profile URL']] as const).map(([key,label])=><div className="field-card" key={key}><label htmlFor={key}>{label}</label><Input id={key} type={key==='email'?'email':'text'} value={state.data.contact[key]} disabled={busy} onChange={e=>contact(key,e.target.value)}/></div>)}</TabsContent>
 <TabsContent value="galleries"><div className="tab-intro"><h2>Case-study image galleries</h2><p>Add full-width artwork below each main case-study image. Arrange images in the order you want clients to see them.</p></div>{['1','2','3','4'].map(key=><section className="gallery-editor" key={key}><h3>Case study {key}</h3><div className="gallery-items">{state.data.galleries[key].map((item,index)=><article className="gallery-item" key={index}><img src={item.src} alt={item.alt}/><div><label htmlFor={`alt-${key}-${index}`}>Image description</label><Input id={`alt-${key}-${index}`} disabled={busy} value={item.alt} onChange={e=>gallery(key,state.data.galleries[key].map((g,i)=>i===index?{...g,alt:e.target.value}:g))}/><label htmlFor={`caption-${key}-${index}`}>Caption</label><Textarea id={`caption-${key}-${index}`} disabled={busy} value={item.caption} onChange={e=>gallery(key,state.data.galleries[key].map((g,i)=>i===index?{...g,caption:e.target.value}:g))}/><div className="gallery-tools"><Button variant="outline" size="icon" aria-label="Move image up" disabled={index===0||busy} onClick={()=>{const list=[...state.data.galleries[key]];[list[index-1],list[index]]=[list[index],list[index-1]];gallery(key,list)}}><ArrowUp/></Button><Button variant="outline" size="icon" aria-label="Move image down" disabled={index===state.data.galleries[key].length-1||busy} onClick={()=>{const list=[...state.data.galleries[key]];[list[index+1],list[index]]=[list[index],list[index+1]];gallery(key,list)}}><ArrowDown/></Button><Button variant="ghost" disabled={busy} onClick={()=>gallery(key,state.data.galleries[key].filter((_,i)=>i!==index))}><X size={16}/> Remove</Button></div></div></article>)}</div><label htmlFor={'gallery-upload-'+key}>{uploading==='gallery-'+key?'Uploading…':'Add an image'}</label><Input id={'gallery-upload-'+key} type="file" accept="image/png,image/jpeg,image/webp,image/gif" disabled={!!uploading||busy||state.data.galleries[key].length>=30} onChange={e=>{upload(e.target.files?.[0],'gallery-'+key,src=>gallery(key,[...state.data.galleries[key],{src,alt:'',caption:''}]));e.target.value=''}}/></section>)}</TabsContent>
 </Tabs></main></div></div>
}
